In [1]:
import numpy

In [3]:
import numpy as np

In [4]:
import numpy as np

print(np.__version__)

1.24.3


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [6]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
import numpy as np

arr = np.array([[1, 2], [3, 4, 5]])

print(arr)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [16]:
import numpy as np

arr = np.array([[1, 2, -5], [4, 5, 6]])

print(arr)

[[ 1  2 -5]
 [ 4  5  6]]


In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5] n.dim=5)

print(arr)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2307429423.py, line 3)